# ==================================
# SERVER CONFIGURATION
# ==================================
server.port=8080
spring.application.name=hb

# JWT secret & expiration
jwt.secret=ReplaceWithYourVerySecretKey_ChangeMe
jwt.expiration-ms=3600000

# ==================================
# JPA CONFIGURATION
# ==================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# = THYMELEAF CONFIGURATION
# ===============================
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# = LOGGING
# ===============================
logging.level.org.springframework=INFO

# ==================================
# DATABASE CONFIGURATION (PostgreSQL)
# ==================================
spring.datasource.url=jdbc:postgresql://localhost:5432/asg_hb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

